name: ServerCorePaper
version: '${project.version}'
main: me.dodo.servercorepaper.ServerCorePaper
api-version: 1.19
authors: [ dodoflix ]
description: Server Core for paper servers.

commands:
  rtp:
    permission: servercore.rtp
    aliases:
      - randomteleport
      - randomtp